routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true, 'register' => false]);

Route::middleware(['auth', 'verified'])->group(function () {

	Route::get('/home', 'HomeController@index')->name('home');
	// Route::get('/perfil', 'PerfilController@index')->name('perfil');
	Route::resource('examens', 'ExamenController');
    Route::resource('pacientes', 'PacienteController');
    Route::resource('resultados', 'ResultadoController');
    Route::resource('estudios', 'EstudioController');
    Route::get('/paciente/eliminar/{id}', 'PacienteController@destroy');
    Route::get('estudios_crear/{id}', 'EstudioController@crear')->name('estudios.crear');
    Route::get('estudios_paciente/{paciente}', 'EstudioController@listaPaciente')->name('estudios.paciente');


});

app/Paciente.php
<?php

namespace App;
use Carbon\Carbon;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Paciente extends Model
{
    //
    use SoftDeletes;
    protected $fillable = [
        'nombre', 'apellido', 'fecha', 'email', 'telefono', 'direccion', 'dni',
    ];

    public function estudios()
    {
        return $this->hasMany('App\Estudio');
    }

    public function edad()
    {
        return Carbon::parse($this->fecha)->age;
    }
}

app/Http/Controllers/PacienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Paciente;
use Illuminate\Support\Facades\Validator;
use Carbon\Carbon;

class PacienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $pacientes = Paciente::orderBy('nombre')->get();

        return view('paciente.lista')->with('pacientes', $pacientes);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $paciente = null;
        return view('paciente.formulario')->with('paciente', $paciente);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        /*$validator = Validator::make($request->all(), [
          'dni'               => 'required|string|min:6|unique:pacientes|',
          'nombre'            => 'required|string|min:3|',
          'apellido'          => 'required|string|min:3|',
          'fecha'             => 'required|date|',
          'email'             => 'nullable|email|unique:pacientes|',
          'telefono'          => 'nullable|string|min:10|',
          'direccion'         => 'nullable|string|min:4'
        ]);

        if($validator->fails()){
            return response()->json([
                'status'  =>'error',
                'message' =>$validator->errors(),
                'a'=>$request->all()
            ], 400);
        }*/
        $this->validate($request,
           [
            'dni'               => 'required|string|min:6|unique:pacientes|',
            'nombre'            => 'required|string|min:3|',
            'apellido'          => 'required|string|min:3|',
            'fecha'             => 'required|date|',
            'email'             => 'nullable|email|unique:pacientes|',
            'telefono'          => 'nullable|string|min:10|',
            'direccion'         => 'nullable|string|min:4'
           ],
        [
            'dni.unique' => 'Documento ya se encuentra registrado.'
        ]);

        $paciente = Paciente::create([
            'dni' 			        =>	$request->dni,
            'nombre' 			    =>	$request->nombre,
            'apellido'		        =>	$request->apellido,
            'fecha'                 =>  $request->fecha,
            'email' 			    =>	$request->email,
            'telefono'		        =>	$request->telefono,
            'direccion'             =>  $request->direccion
        ]);

        return redirect('pacientes');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $paciente = Paciente::where('dni',$id)->get();
        //dd($paciente);
    // if($paciente == null)
    //$paciente->fecha = Carbon::parse($paciente->fecha)->age;
    //dd($paciente);
        return $paciente;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $paciente = Paciente::findOrFail($id);
        return view('paciente.formulario')->with('paciente', $paciente);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $validator = Validator::make($request->all(), [
            'dni'               => 'required|string|min:6|unique:pacientes,dni,'.$id,
            'nombre'            => 'required|string|min:3|',
            'apellido'          => 'required|string|min:3|',
            'fecha'             => 'required|date|',
            'email'             => 'nullable|email|unique:pacientes,email,'.$id,
            'telefono'          => 'nullable|string|min:10|',
            'direccion'         => 'nullable|string|min:4'
          ]);

          if($validator->fails()){
              return response()->json([
                  'status'  =>'error',
                  'message' =>$validator->errors(),
                  'a'=>$request->all()
              ], 400);
          }
        $paciente = Paciente::findOrFail($id);
        $paciente->fill($request->all());
        $paciente->save();

        return redirect('pacientes');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if(is_null($id) ){
            return response()->json([
                'status'  =>'error',
                'message' =>$validator->errors(),
                'a'=>$request->all()
            ], 400);
        }
         $paciente = Paciente::findOrFail($id);
         $paciente->delete();
         return redirect('pacientes');

    }
}

resources/views/paciente/formulario.blade.php
@extends('layouts.master')
@section('contenedor')
<div class="form-group" style="margin: 4%;">
    <form action="{{ ($paciente!= null)? url('pacientes/'.$paciente->id) : route('pacientes.store') }}" method="POST">
    @csrf
    @if ($paciente!= null)
        @method('PUT')
    @endif
    <div class="row">
        <div class="col-xs-12">
            <label for="dni">Documento de identidad</label>
            <input type="text" name="dni" id="dni" class="form-control" value="{{($paciente!= null)?  $paciente->dni : old('dni')}}">
            <strong class="text-danger">{{ $errors->first('dni') }}</strong>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre" id="nombre" class="form-control" value="{{($paciente!= null)?  $paciente->nombre : ''}}">
            <strong class="text-danger">{{ $errors->first('nombre') }}</strong>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <label for="apellido">Apellido</label>
            <input type="text" name="apellido" id="apellido" class="form-control" value="{{($paciente!= null)?  $paciente->apellido : ''}}">
        </div>
    </div>
    <div class="row">
            <div class="col-xs-12">
                <label for="fecha">Fecha de nacimiento</label>
                <input type="date" name="fecha" id="fecha" class="form-control" style="width: 100%;" value="{{($paciente!= null)?  $paciente->fecha : ''}}">
            </div>
        </div>
    <div class="row">
        <div class="col-xs-12">
            <label for="email">E-mail</label>
            <input type="email" name="email" id="email" class="form-control" value="{{($paciente!= null)?  $paciente->email : ''}}">
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <label for="telefono">Telefono</label>
            <input type="text" name="telefono" id="telefono" class="form-control" value="{{($paciente!= null)?  $paciente->telefono : ''}}">
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <label for="direccion">Dirección</label>
            <input type="text" name="direccion" id="direccion" class="form-control" value="{{($paciente!= null)?  $paciente->direccion : ''}}">
        </div>
    </div>
    <div class="row">
            <div class="col-xs-6">
                <a href="{{ route('pacientes.index')}}">
                    <button type="button" class="btn btn-danger" >Cancelar</button>
                </a>

            </div>
        <div class="col-xs-6">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </div>
    </form>
</div>
@endsection

resources/views/paciente/lista-estudio.blade.php
@extends('layouts.master')
@section('contenedor')
<div  style="margin: 4%;">
  <div class="row">
    <div class="col-xs-3">
        <label for="dni">Documento de identidad</label>
        <input type="text" name="dni" id="dni" class="form-control" value="{{  isset($paciente)?  $paciente->dni : old('dni')}}" readonly>
    </div>
    <div class="col-xs-8">
        <label for="nombre">Nombre y Apellido</label>
        <input type="text" name="nombre" id="nombre" class="form-control" value="{{isset($paciente)?  $paciente->nombre.' '.$paciente->apellido : old('nombre')}}" readonly>
    </div>
    <div class="col-xs-1">
      <label for="nombre">Edad</label>
      <input type="text" name="edad" id="edad" class="form-control" value="{{isset($paciente)?  $paciente->edad(): old('edad')}}" readonly>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <label for="dni">Teléfono</label>
      <input type="text" name="telefono" id="telefono" class="form-control" value="{{  isset($paciente)?  $paciente->telefono : old('telefono')}}" readonly>
    </div>
    <div class="col-xs-4">
      <label for="dni">E-mail</label>
      <input type="text" name="email" id="email" class="form-control" value="{{  isset($paciente)?  $paciente->email : old('email')}}" readonly>
    </div>
    <div class="col-xs-4">
      <label for="dni">Dirección</label>
      <input type="text" name="direccion" id="direccion" class="form-control" value="{{  isset($paciente)?  $paciente->direccion : old('direccion')}}" readonly>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-xs-12">
        <table class="table" >
          <thead class="thead-light">
            <tr>
              <th scope="col">Examenes</th>
              <th scope="col">Fecha</th>
              <th scope="col">Estado</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
              @isset($estudios)
                @foreach ($estudios as $estudio)
                <tr>
                    <td>
                            {{sizeof($estudio->resultados)}}
                    </td>
                    <td>
                            {{date_format($estudio->created_at, 'd/m/Y g:i A')}}
                    </td>
                    <td>
                        {{$estudio->estado}}
                    </td>
                    <td style="display: inline-flex;">
                            <a href="{{ url('estudios/'.$estudio->id.'/edit')}}" class="btn btn-primary">Ver/Editar</a>
                            <form method="POST" action="{{ route('estudios.destroy', $estudio->id)}}">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">
                                    Eliminar
                                </button>
                            </form>
                        </td>
                </tr>
                @endforeach
              @endisset
          </tbody>
        </table>
    </div>
  </div>
  <div class="row">
        <div class="col-xs-6">
            <a href="{{ route('home')}}">
                <button class="btn btn-danger" onclick="{{ route('home')}}">Regresar</button>
            </a>
        </div>
        <div class="col-xs-6">
          <a href="{{ route('estudios.create')}}">
            <button class="btn btn-success" >Registrar</button>
          </a>
        </div>
  </div>
</div>
@endsection

resources/views/paciente/lista.blade.php
@extends('layouts.master')
@section('contenedor')
<div  style="margin: 4%;">
  <div class="row">
    <div class="col-xs-12">
        <table class="table" border>
          <thead class="thead-light">
            <tr>
              <th scope="col">Doc. de identidad</th>
              <th scope="col">Nombre</th>
              <th scope="col">Apellido</th>
              <th scope="col">Fecha de Nac.</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
              @foreach ($pacientes as $paciente)
              <tr>
                <th scope="row">{{$paciente->dni}}</th>
                <td>{{$paciente->nombre}}</td>
                <td>{{$paciente->apellido}}</td>
                <td>{{$paciente->edad()}}</td>
                <td style="display: inline-flex;">
                  <a href="{{ url('pacientes/'.$paciente->id.'/edit')}}" class="btn btn-primary">Editar</a>
                  <form method="POST" action="{{ route('pacientes.destroy', $paciente->id)}}">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" type="submit">
                      Eliminar
                    </button>
                  </form>
                  <a href="{{ route('estudios.paciente', $paciente->id)}}" class="btn btn-success">Estudios</a>
                </td>
              </tr>
              @endforeach
          </tbody>
        </table>
    </div>
  </div>
  <div class="row">
        <div class="col-xs-6">
            <a href="{{ route('home')}}">
                <button class="btn btn-danger" onclick="{{ route('home')}}">Regresar</button>
            </a>
        </div>
        <div class="col-xs-6">
          <a href="{{ route('pacientes.create')}}">
            <button class="btn btn-success" onclick="{{ route('pacientes.create')}}">Registrar</button>
          </a>
        </div>
  </div>
</div>
@endsection