routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true, 'register' => false]);

Route::middleware(['auth', 'verified'])->group(function () {

	Route::get('/home', 'HomeController@index')->name('home');
	// Route::get('/perfil', 'PerfilController@index')->name('perfil');
	Route::resource('examens', 'ExamenController');
    Route::resource('pacientes', 'PacienteController');
    Route::resource('resultados', 'ResultadoController');
    Route::resource('estudios', 'EstudioController');
    Route::get('/paciente/eliminar/{id}', 'PacienteController@destroy');
    Route::get('estudios_crear/{id}', 'EstudioController@crear')->name('estudios.crear');
    Route::get('estudios_paciente/{paciente}', 'EstudioController@listaPaciente')->name('estudios.paciente');


});

app/Examen.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Examen extends Model
{
    //
    use SoftDeletes;
    protected $fillable = [
        'nombre', 'estado', 'descripcion',
    ];

    public function resultados()
    {
        return $this->hasMany('App\Resultado');
    }
}

app/Http/Controllers/ExamenController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Examen;

class ExamenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $examenes = Examen::orderBy('nombre')->get();

        return view('examen.lista')->with('examenes', $examenes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('examen.formulario');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,
           [
            'nombre'               => 'required|string|min:2|unique:examens|',
            'descripcion'          => 'nullable|string|min:3|',
            'estado'                => 'required|string|'
           ],
        [
            'nombre.unique' => 'Este examen ya se encuentra registrado.'
        ]);

        $examen = Examen::create([
            'nombre' 			        =>	$request->nombre,
            'descripcion' 			    =>	$request->descripcion,
            'estado'		            =>	$request->estado
        ]);

        return redirect('examens');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $examen = Examen::findOrFail($id);

        return view('examen.formulario')->with('examen', $examen);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,
           [
            'nombre'               => 'required|string|min:2|unique:examens,nombre,'.$id,
            'descripcion'          => 'nullable|string|min:3|',
            'estado'               => 'required|string|'
           ],
        [
            'nombre.unique' => 'Este examen ya se encuentra registrado.'
        ]);

        $examen = Examen::findOrFail($id);
        $examen->fill($request->all());
        $examen->save();

        return redirect('examens');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if(is_null($id) ){
            return response()->json([
                'status'  =>'error',
                'message' =>$validator->errors(),
                'a'=>$request->all()
            ], 400);
        }
         $examen = Examen::findOrFail($id);
         $examen->delete();
         return redirect('examens');
    }
}

resources/views/examen/formulario.blade.php
@extends('layouts.master')
@section('contenedor')
<div class="form-group" style="margin: 4%;">
    <form action="{{ isset($examen)? route('examens.update', $examen->id) : route('examens.store') }}" method="POST">
    @csrf
    @if (isset($examen))
        @method('PUT')
    @endif
    <div class="row">
        <div class="col-xs-12">
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre" id="nombre" class="form-control" value="{{isset($examen)?  $examen->nombre : ''}}">
            <strong class="text-danger">{{ $errors->first('nombre') }}</strong>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <label for="apellido">Descripción</label>
            <textarea name="descripcion" id="descripcion"  rows="3" class="form-control">{{isset($examen)?  $examen->descripcion : ''}}</textarea>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
        <label for="apellido">Estado</label>
            <select name="estado" id="estado" class="form-control">
                <option value="DISPONIBLE">DISPONIBLE</option>
                <option value="NO DISPONIBLE">NO DISPONIBLE</option>
                <option value="FALTA MATERIAL">FALTA MATERIAL</option>
                <option value="OTRO">OTRO</option>
            </select>
        </div>
    </div>
    <div class="row">
            <div class="col-xs-6">
                <a href="{{ route('examens.index')}}">
                    <button type="button" class="btn btn-danger" >Cancelar</button>
                </a>

            </div>
        <div class="col-xs-6">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </div>
    </form>
</div>
@endsection

resources/views/examen/lista.blade.php
@extends('layouts.master')
@section('contenedor')
<div  style="margin: 4%;">
  <div class="row">
    <div class="col-xs-12">
        <table class="table" >
          <thead class="thead-light">
            <tr>
              <th scope="col">Examen</th>
              <th scope="col">Descripción</th>
              <th scope="col">Estado</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
              @foreach ($examenes as $examen)
              <tr>
                  <th scope="row">{{$examen->nombre}}</th>
                  <td>{{$examen->descripcion}}</td>
                  <td>{{$examen->estado}}</td>
                  <td style="display: inline-flex;">
                      <a href="{{ url('examens/'.$examen->id.'/edit')}}" class="btn btn-primary">Editar</a>
                      <form method="POST" action="{{ route('examens.destroy', $examen->id)}}">
                          @csrf
                          @method('DELETE')
                          <button class="btn btn-danger" type="submit">
                              Eliminar
                          </button>
                      </form>
                  </td>
              </tr>
              @endforeach
          </tbody>
        </table>
    </div>
  </div>
  <div class="row">
        <div class="col-xs-6">
            <a href="{{ route('home')}}">
                <button class="btn btn-danger" onclick="{{ route('home')}}">Regresar</button>
            </a>
        </div>
        <div class="col-xs-6">
          <a href="{{ route('examens.create')}}">
            <button class="btn btn-success" >Registrar</button>
          </a>
        </div>
  </div>
</div>
@endsection