routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true, 'register' => false]);

Route::middleware(['auth', 'verified'])->group(function () {

	Route::get('/home', 'HomeController@index')->name('home');
	// Route::get('/perfil', 'PerfilController@index')->name('perfil');
	Route::resource('examens', 'ExamenController');
    Route::resource('pacientes', 'PacienteController');
    Route::resource('resultados', 'ResultadoController');
    Route::resource('estudios', 'EstudioController');
    Route::get('/paciente/eliminar/{id}', 'PacienteController@destroy');
    Route::get('estudios_crear/{id}', 'EstudioController@crear')->name('estudios.crear');
    Route::get('estudios_paciente/{paciente}', 'EstudioController@listaPaciente')->name('estudios.paciente');


});

app/Estudio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Estudio extends Model
{
    //
    use SoftDeletes;
    protected $fillable = [
        'estado', 'paciente_id',
    ];

    public function paciente()
    {
        return $this->belongsTo('App\Paciente', 'paciente_id');
    }

    public function resultados()
    {
        return $this->hasMany('App\Resultado');
    }

    /*protected static function boot() {
        parent::boot();

        static::deleting(function($estudio) { // before delete() method call this
             $estudio->resultados()->delete();
             // do the rest of the cleanup...
        });
    }*/
}

app/Http/Controllers/EstudioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Paciente;
use App\Examen;
use App\Resultado;
use App\Estudio;

class EstudioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        //$estudios = Estudio::with('resultados')->with('paciente')->orderBy('nombre')->get();
        $estudios = Estudio::with('resultados')->with('paciente')->orderBy('created_at', 'desc')->get();
        //$estudios = Estudio::orderBy('created_at', 'desc')->get();
        //dd($estudios);

        return view('estudio.lista')->with('estudios', $estudios);
    }

    public function listaPaciente($paciente_id)
    {
        //
        $paciente = Paciente::findOrFail($paciente_id);
        //$estudios = Estudio::with('resultados')->with('paciente')->orderBy('nombre')->get();
        $estudios = Estudio::where('paciente_id',$paciente_id)->with('resultados')->orderBy('created_at', 'desc')->get();
        //$estudios = Estudio::orderBy('created_at', 'desc')->get();
        //dd($estudios);
        //dd($estudios);

        return view('paciente.lista-estudio')->with('estudios', $estudios)->with('paciente', $paciente);
    }

    public function crear($id)
    {
        //
        $paciente = Paciente::findOrFail($id);
        $examenes = Examen::orderBy('nombre')->get();
        // dd($paciente);
        return view('estudio.formulario')->with('paciente', $paciente)->with('examenes', $examenes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $examenes = Examen::orderBy('nombre')->get();
        return view('estudio.formulario')->with('examenes', $examenes);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        /*$this->validate($request,
        [
         'dni'               => 'required|string|min:6|unique:pacientes|',
         'nombre'            => 'required|string|min:3|',
         'apellido'          => 'required|string|min:3|',
         'fecha'             => 'required|date|',
         'email'             => 'nullable|email|unique:pacientes|',
         'telefono'          => 'nullable|string|min:10|',
         'direccion'         => 'nullable|string|min:4'
        ],
     [
         'dni.unique' => 'Documento ya se encuentra registrado.'
     ]);*/
       $this->validate($request,
           [
            'paciente'           => 'required|string|min:1|',
            'estado'            => 'required|string|min:1|',
            'estudio'            => 'required|array|min:1',
            'estudio.*.examen'   => 'required|string|min:1|',
            'estudio.*.valor'   => 'nullable|string|min:1|'

           ],
        [
            'paciente.required' => 'Debe buscar un Doc. de identidad.',
            'estudio.required' => 'Debe agregar al menos un examen.'
        ]);

        $estudio = Estudio::create([
            'estado'        => $request->estado,
            'paciente_id'   => $request->paciente
        ]);
        //dd($estudio);

        foreach ($request->estudio as $estdios) {
            $resultados = Resultado::create([
                'estudio_id' => $estudio->id,
                'examen_id' => $estdios['examen'],
                'valor' => $estdios['valor']
            ]);
        }
        //dd($request);
        return redirect('estudios');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        //$paciente = Paciente::where('dni',$id)->get();
        $estudio = (Estudio::where('id',$id)->with('resultados')->get())[0];
        //dd($estudio->paciente_id);
        $paciente = Paciente::findOrFail($estudio->paciente_id);
        //dd($paciente);
        $resultados = array();
        foreach ($estudio->resultados as $result) {
            //dd($result->id);
            //dd((Resultado::where('id', $result->id)->with('examen')->get())[0]);
            $resultados[$result->id] = (Resultado::where('id', $result->id)->with('examen')->get())[0];
        }
        //dd($resultados);
        $examenes = Examen::orderBy('nombre')->get();
        // dd($paciente);
        return view('estudio.formulario')
        ->with('paciente', $paciente)
        ->with('examenes', $examenes)
        ->with('estudio', $estudio)
        ->with('resultados', $resultados);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        //dd($request);
        if(is_null($id) ){
            return response()->json([
                'status'  =>'error',
                'message' =>$validator->errors(),
                'a'=>$request->all()
            ], 400);
        }
        //dd($id);
       $this->validate($request,
           [
            'paciente'              => 'required|string|min:1|',
            'estado'                => 'required|string|min:1|',
            'estudio'               => 'required|array|min:1',
            'estudio.*.resultado'   => 'nullable|string|min:1|',
            'estudio.*.examen'      => 'required|string|min:1|',
            'estudio.*.valor'       => 'nullable|string|min:1|',
            'eliminados'            => 'nullable|array|min:1',
            'eliminados.*.examen'   => 'required|string|min:1|',

           ],
        [
            'paciente.required' => 'Debe buscar un Doc. de identidad.',
            'estudio.required' => 'Debe agregar al menos un examen.'
        ]);

        $estudio = Estudio::findOrFail($id);
        //dd($estudio);
        $estudio->estado = $request->estado;
        //dd($estudio);
        $estudio->save();

        //dd($estudio);
        //dd($request->eliminados);
        if (isset($request->eliminados)) {
            foreach ($request->eliminados as $examen) {
                $resultado = Resultado::findOrFail($examen['examen']);
                $resultado->delete();
            }
        }
        //dd($request->estudio);
        foreach ($request->estudio as $estudios) {
            //dd($estudios['resultado']);
            if ($estudios['resultado'] === 'null') {
                //dd($estudios);
                $resultado = Resultado::create([
                    'estudio_id' => $id,
                    'examen_id' => $estudios['examen'],
                    'valor' => $estudios['valor']
                ]);
                //dd($resultado);
            }
            else {
                $resultado = Resultado::findOrFail($estudios['resultado']);
                //dd($resultado);
                $resultado->valor = $estudios['valor'];
                $resultado->save();
            }
        }

        return redirect('estudios');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if(is_null($id) ){
            return response()->json([
                'status'  =>'error',
                'message' =>$validator->errors(),
                'a'=>$request->all()
            ], 400);
        }
         $estudio = Estudio::findOrFail($id);
         //$estudio->resultados->delete();
         $estudio->delete();
         return redirect('estudios');
    }
}

resources/views/estudio/formulario.blade.php
@extends('layouts.master')
@section('contenedor')
<div class="form-group" style="margin: 4%;">
    <div class="row">
        <div class="col-xs-3">
            <label for="dni">Documento de identidad</label>
            <input type="text" name="dni" id="dni" class="form-control" value="{{isset($paciente)?  $paciente->dni : old('dni')}}"
            @if (isset($paciente))
            disabled
            @endif>
            <strong class="text-danger" id="errordni"></strong>
            <strong class="text-danger">{{ $errors->first('paciente') }}</strong>
        </div>
        <div class="col-xs-1" style="align-self: end;">
            @if (!isset($paciente))
                <button type="button" id="buscar"class="btn btn-success">Buscar</button>
            @endif
        </div>
        <div class="col-xs-5">
            <label for="nombre">Nombre y Apellido</label>
            <input type="text" name="nombre" id="nombre" class="form-control" value="{{isset($paciente)?  $paciente->nombre.' '.$paciente->apellido : ''}}" disabled>
        </div>
        <div class="col-xs-1">
            <label for="apellido">Edad</label>
            <input type="text" name="edad" id="edad" class="form-control" value="{{isset($paciente)?  $paciente->edad() : ''}}" disabled>
        </div>
        <div class="col-xs-2">
            <label for="telefono">Telefono</label>
            <input type="text" name="telefono" id="telefono" class="form-control" value="{{isset($paciente)?  $paciente->telefono : ''}}" disabled>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-5">
            <label for="telefono">Examen</label>
            <select name="examen" id="examen" class="form-control">
                <option value="Seleccione un examen">Seleccione un examen</option>
                @foreach($examenes as $examen)
                    <option value="{{$examen->id}}" {{$examen->estado=='DISPONIBLE'? '' : 'disabled'}}>{{$examen->nombre}}</option>
                @endforeach
            </select>
            <strong class="text-danger" id="errorExamen"></strong>
        </div>
        <div class="col-xs-2" style="align-self: center;">
            <a href="javascript:;" id="agregar" class="btn btn-success">Agregar</a>
        </div>
        <div class="col-xs-5">
            <label for="telefono">Estado</label>
            <select name="estado" id="estado" class="form-control">
                <option value="Por realizar">Por realizar</option>
                <option value="Realizado">Realizado</option>
                <option value="Impreso">Impreso</option>
                <option value="Entregado">Entregado</option>
            </select>
            <strong class="text-danger" >{{ $errors->first('estado') }}</strong>
        </div>
    </div
    </form>
    <form method="POST" action="{{isset($estudio) ? route('estudios.update', $estudio->id) : route('estudios.store')}}" class="form-group">
            @csrf
            @isset($estudio)
                @method('PUT')
            @endisset
            <input type="hidden" name="paciente" id="paciente" value="{{isset($paciente) ? $paciente->id : ''}}">
            <div class="row">
                <div class="col-xs-12">
                    <table class="table" id="tabla">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Examen</th>
                            <th scope="col">Valor</th>
                            <th scope="col">Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                            @isset($resultados)
                                @foreach ($resultados as $resultado)
                                <tr id="fila{{$resultado->examen_id}}">
                                    <input type="hidden" name="estudio[{{$resultado->id}}][resultado]" id="ev{{$resultado->examen_id}}" value="{{$resultado->id}}">
                                    <input type="hidden" name="estudio[{{$resultado->id}}][examen]" id="ev{{$resultado->examen_id}}" value="{{$resultado->examen_id}}">
                                    <td><input class="form-control" type="text" name="estudio[{{$resultado->id}}][examenTexto]" value="{{$resultado->examen['nombre']}}" readonly></td>
                                    <td><input class="form-control" type="text" name="estudio[{{$resultado->id}}][valor]" value="{{$resultado->valor}}"></td>
                                    <td><button type="button" class="btn btn-danger" onClick="Eliminar({{$resultado->examen_id}}, {{$resultado->id}})">Eliminar</button></td>
                                </tr>
                                @endforeach
                            @endisset
                        </tbody>
                    </table>
                    <strong class="text-danger">{{ $errors->first('estudio') }}</strong>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6">
                    <a href="{{ route('estudios.index')}}">
                        <button type="button" class="btn btn-danger" >Cancelar</button>
                    </a>
                </div>
                <div class="col-xs-6">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
            <div style="display:" id="eliminados"

            </div>

        </form>
</div>

@endsection
@section('fin')
<script type="text/javascript">
    let table = $('#tabla');
    let eliminados = $('#eliminados');
    let tableFila = $('#tabla >tr');
    let examenes = [];
    let editando = false;
    $('#agregar').click(function(){
        agregar();
    });
    /*$('#tblUsuario tr').each(function () {

    }*/
    $.each($('input'),function(i,val){
        if($(this).attr("type")=="hidden"){
            let valor = $(this).attr("id") + '';
            //let cadena = valor.split('-',2);
            //console.log(valor, $(this).attr("name"), $(this).attr("value"));
            if(valor === 'ev'+$(this).attr("value")) {
                Selector($(this).attr("value"), false);
                if (!editando) editando = true;
                console.log(valor, $(this).attr("name"), $(this).attr("value"));
            }
            /*if(cadena.length>1) {

                $(this).attr("value")
            }*/
            //console.log(cadena);
            //var valueOfHidFiled=$(this).attr("id");
            //console.log(valueOfHidFiled, $(this).attr("name"), $(this).attr("value"));
        }
    });
    $('#buscar').click(function(){
        Buscar();
    });
       /* $("td").each(function(){
            console.log($(this).find("input:hidden").attr('value'));
            if('estudio[6][examen]' === $(this).children("input").attr('name')) {
                console.log($(this).children("input").attr('value'));
            }
        });*/
    //change()

    function agregar() {
        let examen=$('#examen').val();
        //console.log('Indice', examenes.indexOf(examen), examen);
        if(examenes.indexOf(examen) === -1 && examen != null && examen != 'Seleccione un examen') {
            //examenes.push(examen);
            //let valor=$('#valor').val();
            let examenTexto=$('#examen option:selected').text();
            Selector(examen, false);
            //$("#examen option[value=" +examen + "]").hide();
            //let bloqueo=$('#examen option:selected').prop('disabled', 'disabled');
            //$('select[name="lineas"] option:selected').text());
            let i = $('#tabla tr').length ;
            //console.log(examenTexto);
            let fila='<tr id="fila'+examen+'">'+
            '<input type="hidden" name="estudio['+examen+'][resultado]"  value="null">'+
            '<input type="hidden" name="estudio['+examen+'][examen]" id="ev'+examen+'" value="'+examen+'">'+
            '<td><input class="form-control" type="text" name="estudio['+examen+'][examenTexto]" value="'+examenTexto+'" readonly></td>'+
            '<td><input class="form-control" type="text" name="estudio['+examen+'][valor]" value="" ></td>'+
            '<td><button type="button" class="btn btn-danger" onClick="Eliminar('+examen+', null)">Eliminar</button></td>'+
            '</tr>';
            //console.log(examenes);
            table.append(fila);
            $('#examen').val('Seleccione un examen');
            $('#errorExamen').text('');
           // $("#examen >option[value='Seleccione un examen']").attr("selected", true);
            //$("#examen >option[value='Seleccione un examen']").attr("selected", false);
        }
        else {
            $('#errorExamen').text('Debe seleccionar un examen válido.');
        }
    }

    function Eliminar(i, resultado) {

        //let vid = '#ev'+i;
        console.log('indice', i );
        let valorExamen=  i+'';//$('#ev'+i).val();
        /*console.log('valorExamen', valorExamen);*/
        console.log('examenes', examenes);
        console.log(examenes.indexOf(valorExamen));
        //examenes.splice(examenes.indexOf(valorExamen), 1);

        Selector(valorExamen, true);
        console.log('examenes', examenes);
        if (editando && resultado != null) {
            let fila= '<input type="hidden" name="eliminados['+resultado+'][examen]" id="ee'+resultado+'" value="'+resultado+'">';
            eliminados.append(fila);
        }
        //$("#examen option[value=" +valorExamen + "]").show();
        $('#fila'+i).remove();
        //document.getElementById("tabla").deleteRow(i);
        //tableFila.remove(i);
    }

    function Selector(valor, estado) {
        if(estado){
            $("#examen option[value=" + valor + "]").show();
            examenes.splice(examenes.indexOf(valor), 1);
        }
        else {
            $("#examen option[value=" + valor + "]").hide();
            examenes.push(valor);
        }
    }

    function Buscar() {
        $.ajax({
            // En data puedes utilizar un objeto JSON, un array o un query string
            //data: {$('#dni').val()},
            //Cambiar a type: POST si necesario
            type: "GET",
            // Formato de datos que se espera en la respuesta
            dataType: "json",
            // URL a la que se enviará la solicitud Ajax
            url: "http://127.0.0.1:8000/pacientes/"+$('#dni').val(),
        })
         .done(function( data, textStatus, jqXHR ) {
             console.log(jqXHR);
             if(jqXHR.responseJSON.length > 0) {
                 paciente = jqXHR.responseJSON[0];
                $('#paciente').val(paciente.id);
                $('#nombre').val(paciente.nombre+' '+paciente.apellido);
                $('#edad').val(Edad(paciente.fecha));
                $('#telefono').val(paciente.telefono);
             } else {
                $('#errordni').text('Doc. de identidad no registrado.');
                $('#paciente').val(null);
             }

         })
         .fail(function( jqXHR, textStatus, errorThrown ) {
             if ( console && console.log ) {
                 console.log( "La solicitud a fallado: " +  textStatus);
             }
        });
    }

    function Edad(FechaNacimiento) {
        var fechaNace = new Date(FechaNacimiento);
        var fechaActual = new Date()
        var mes = fechaActual.getMonth();
        var dia = fechaActual.getDate();
        var año = fechaActual.getFullYear();
        fechaActual.setDate(dia);
        fechaActual.setMonth(mes);
        fechaActual.setFullYear(año);
        edad = Math.floor(((fechaActual - fechaNace) / (1000 * 60 * 60 * 24) / 365));
        return edad;
    }
</script>

@endsection

resources/views/estudio/lista.blade.php
@extends('layouts.master')
@section('contenedor')
<div  style="margin: 4%;">
  <div class="row">
    <div class="col-xs-12">
        <table class="table" >
          <thead class="thead-light">
            <tr>
              <th scope="col">Paciente</th>
              <th scope="col">Examenes</th>
              <th scope="col">Fecha</th>
              <th scope="col">Estado</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
              @foreach ($estudios as $estudio)
              <tr>
                  <td>
                        {{$estudio->paciente['nombre'].' '.$estudio->paciente['apellido']}}
                  </td>
                  <td>
                        {{sizeof($estudio->resultados)}}
                  </td>
                  <td>
                        {{date_format($estudio->created_at, 'd/m/Y g:i A')}}
                  </td>
                  <td>
                       {{$estudio->estado}}
                  </td>
                  <td style="display: inline-flex;">
                        <a href="{{ url('estudios/'.$estudio->id.'/edit')}}" class="btn btn-primary">Ver/Editar</a>
                        <form method="POST" action="{{ route('estudios.destroy', $estudio->id)}}">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">
                                Eliminar
                            </button>
                        </form>
                        <a href="{{ url('estudios_crear/'.$estudio->paciente['id'])}}" class="btn btn-success">Paciente</a>
                    </td>
              </tr>
              @endforeach
          </tbody>
        </table>
    </div>
  </div>
  <div class="row">
        <div class="col-xs-6">
            <a href="{{ route('home')}}">
                <button class="btn btn-danger" onclick="{{ route('home')}}">Regresar</button>
            </a>
        </div>
        <div class="col-xs-6">
          <a href="{{ route('estudios.create')}}">
            <button class="btn btn-success" >Registrar</button>
          </a>
        </div>
  </div>
</div>
@endsection